---
development:
  cloud_name: yorisilo
  api_key: '327497539423651'
  api_secret: HN0daovs9RroDxA_GptgV9U0OUU
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: yorisilo
  api_key: '327497539423651'
  api_secret: HN0daovs9RroDxA_GptgV9U0OUU
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: yorisilo
  api_key: '327497539423651'
  api_secret: HN0daovs9RroDxA_GptgV9U0OUU
  enhance_image_tag: true
  static_image_support: false
