---
development:
  cloud_name: hl63eioog
  api_key: '165328411917133'
  api_secret: tGTtTnTlh6tWY_v2BpnAEV77em8
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hl63eioog
  api_key: '165328411917133'
  api_secret: tGTtTnTlh6tWY_v2BpnAEV77em8
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hl63eioog
  api_key: '165328411917133'
  api_secret: tGTtTnTlh6tWY_v2BpnAEV77em8
  enhance_image_tag: true
  static_image_support: false
